//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationForm
    {
        public int Id { get; set; }
        public int DisciplineCode { get; set; }
        public string SpecializationNumber { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
